In [2]:
# 사각형 내 상가분석
from urllib.request import Request, urlopen
from urllib.parse import urlencode, quote_plus
import pandas as pd
import json

skey = '2WKhofO%2FP%2Fzyhb%2FYYUq6fVtO08ZFBBiJ%2B7abwe9sV7Y%2BP9sWIADFvAVKjMJc6qln2Kabc6cgEs4anTIddxB7Tg%3D%3D'
res_id = 'store'

def baro_api(skey, res_id, encode):
    stype = 'json'
    url = 'http://apis.data.go.kr/B553077/api/open/sdsc2/baroApi'
    params = f'?ServiceKey={skey}&type={stype}&resId={res_id}&' + encode   
    query = url + params
    
    response = Request(query)
    response.get_method = lambda: 'GET'
    response_body = urlopen(response).read()
    
    response_dict = json.loads(response_body.decode('utf-8'))
    items = response_dict['body']['items']

    df = pd.DataFrame(items)
    return df

In [ ]:
# 역 주변 350m반경 내의 상가정보
# 역 좌표에 경도, 위도 대비 350m만큼의 사각좌표 구하기
def xy(x,y):
    max_x = x + 0.00350
    max_y = y + 0.00350
    min_x = x - 0.00350    
    min_y = y - 0.00350        
    return (min_x, min_y, max_x, max_y)
# xy좌표 값 : 이대역 좌표
min_x, min_y, max_x, max_y = xy(126.945857, 37.556761)

import numpy as np
#좌표로 계산된 지역, 구역 나누기
print(min_x, min_y, max_x, max_y )
li_x = np.linspace(min_x,max_x,20)
li_y = np.linspace(min_y,max_y,20)
#좌표 API 내에 넣고 데이터 프레임 만들기
df_s = np.NaN
for i in range(len(li_x)-1):
    x0 = li_x[i]
    x1 = li_x[i+1]
    for j in range(len(li_y)-1):
        y0 = li_y[j]
        y1 = li_y[j+1]
        
        # #이대역 37.556761, 126.945857
        encode = urlencode({quote_plus('catId'):'rectangle'
                            , quote_plus('minx'):x0, quote_plus('miny'):y0
                            , quote_plus('maxx'):x1, quote_plus('maxy'):y1})

        df_t = baro_api(skey, res_id, encode)
        #print(i, j, type(df_t), len(df_t))

        if type(df_t) == type(pd.DataFrame()) and len(df_t) > 0:        
            if type(df_s) == type(pd.DataFrame()) and len(df_s) > 0:
                #df_s = pd.concat(df_s,df_t, ignore_index=True)
                df_s = pd.concat([df_s, df_t], axis = 0, ignore_index=True)
            else:
                df_s = df_t    

df_s

126.942357 37.553261 126.949357 37.560261000000004

In [15]:
# 데이터프레임 내에 중복값 확인 및 처리
print(df_s.duplicated().sum())

0

In [2]:
df_s.drop_duplicates(inplace = True)
# 중복값 재확인
df_s.duplicated().sum()
df_s.to_json('df_region.json', orient='columns')

NameError: name 'df_s' is not defined

In [14]:
import warnings
warnings.filterwarnings('ignore')
df_s[df_s.indsLclsCd == 'Q'][df_s.bizesNm == '']

Empty DataFrame
Columns: [bizesId, bizesNm, brchNm, indsLclsCd, indsLclsNm, indsMclsCd, indsMclsNm, indsSclsCd, indsSclsNm, ksicCd, ksicNm, ctprvnCd, ctprvnNm, signguCd, signguNm, adongCd, adongNm, ldongCd, ldongNm, lnoCd, plotSctCd, plotSctNm, lnoMnno, lnoSlno, lnoAdr, rdnmCd, rdnm, bldMnno, bldSlno, bldMngNo, bldNm, rdnmAdr, oldZipcd, newZipcd, dongNo, flrNo, hoNo, lon, lat]
Index: []

[0 rows x 39 columns]

In [3]:
df_d = pd.read_json('df_region2.json')
df_d

,bizesId,bizesNm,brchNm,indsLclsCd,indsLclsNm,indsMclsCd,indsMclsNm,indsSclsCd,indsSclsNm,ksicCd,...,bldMngNo,bldNm,rdnmAdr,oldZipcd,newZipcd,dongNo,flrNo,hoNo,lon,lat
0,22414172,브레드칸,,N,관광/여가/오락,N03,연극/영화/극장,N03A06,연극/음악/예술관련기타,,...,1.144011e+24,,서울특별시 마포구 신촌로24안길 16-3,121806,4103,,,,126.942434,37.555489
1,12098251,머리쟁이,,F,생활서비스,F01,이/미용/건강,F01A01,여성미용실,S96112,...,1.144011e+24,,서울특별시 마포구 신촌로 154,121806,4104,,2,,126.942637,37.556347
2,12620998,에이치에비뉴호텔이대점,이대점,O,숙박,O01,호텔/콘도,O01A01,호텔/콘도,,...,1.144011e+24,대성목재,서울특별시 마포구 신촌로 152,121806,4104,,1,,126.942560,37.556238
3,21954392,로뎀원룸리빙텔,,R,학문/교육,R10,도서관/독서실,R10A02,고시원,R90212,...,1.144011e+24,,서울특별시 마포구 신촌로 154,121806,4104,,,,126.942637,37.556347
4,11980901,팔색,,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,1.141011e+24,신촌자이엘라,서울특별시 서대문구 신촌로 149,120809,3780,,1,,126.942483,37.556859
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
952,11755132,파파존스피자,이대아현점,Q,음식,Q06,양식,Q06A01,정통양식/경양식,I56114,...,1.141011e+24,,서울특별시 서대문구 신촌로 207,120822,3767,,2,,126.949133,37.557207
953,12452641,파파존스이대아현점,이대아현점,Q,음식,Q07,패스트푸드,Q07A01,피자전문,I56192,...,1.141011e+24,,서울특별시 서대문구 신촌로 207,120822,3767,,1,,126.949133,37.557207
954,21946384,로신이,,D,소매,D06,가방/신발/액세서리,D06A02,구두제화/캐주얼화,G47420,...,1.141011e+24,,서울특별시 서대문구 신촌로 207,120822,3767,,1,,126.949133,37.557207
955,26159771,뮤즈웨딩,,F,생활서비스,F17,예식/의례/관혼상제,F17A01,예식장/예식서비스,S96991,...,1.141011e+24,,서울특별시 서대문구 신촌로 207,120822,3767,,1,,126.949133,37.557207
956,26288178,아네스,,D,소매,D05,의복의류,D05A01,일반의류,G47416,...,1.141011e+24,링크(LINK),서울특별시 서대문구 신촌로 209,120822,3767,,1,,126.949258,37.557190

In [67]:
df_food = df_d[df_d.indsLclsCd == 'Q']
df_food.rename(columns={'bizesNm':'place'}, inplace = True) 
df_food

,bizesId,place,brchNm,indsLclsCd,indsLclsNm,indsMclsCd,indsMclsNm,indsSclsCd,indsSclsNm,ksicCd,...,bldMngNo,bldNm,rdnmAdr,oldZipcd,newZipcd,dongNo,flrNo,hoNo,lon,lat
4,11980901,팔색,,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,1.141011e+24,신촌자이엘라,서울특별시 서대문구 신촌로 149,120809,3780,,1,,126.942483,37.556859
5,12033685,포원제로410,,Q,음식,Q06,양식,Q06A01,정통양식/경양식,I56114,...,1.141011e+24,신촌자이엘라,서울특별시 서대문구 신촌로 149,120809,3780,,1,,126.942483,37.556859
11,16553616,밥이꿀바비꿀,,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,1.141011e+24,신촌자이엘라,서울특별시 서대문구 신촌로 149,120809,3780,101,,,126.942483,37.556859
12,16701604,투다리,이대점,Q,음식,Q09,유흥주점,Q09A07,기타일반유흥주점,I56211,...,1.141011e+24,신촌자이엘라,서울특별시 서대문구 신촌로 149,120809,3780,,,,126.942483,37.556859
13,16860055,벨르,,Q,음식,Q12,커피점/카페,Q12A01,커피전문점/카페/다방,I56220,...,1.141011e+24,신촌자이엘라,서울특별시 서대문구 신촌로 149,120809,3780,101,,,126.942483,37.556859
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
943,12482161,플러스알파카페,,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,1.141011e+24,핀란드타워,서울특별시 서대문구 신촌로 203,120808,3767,,2,,126.948488,37.557201
944,15958983,마이헬싱키까페,,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,1.141011e+24,핀란드타워,서울특별시 서대문구 신촌로 203,120808,3767,,-2,,126.948488,37.557201
947,26031006,고향순대감자탕,,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,1.144011e+24,,서울특별시 마포구 대흥로24길 50,121870,4123,,1,,126.948656,37.554905
952,11755132,파파존스피자,이대아현점,Q,음식,Q06,양식,Q06A01,정통양식/경양식,I56114,...,1.141011e+24,,서울특별시 서대문구 신촌로 207,120822,3767,,2,,126.949133,37.557207
953,12452641,파파존스이대아현점,이대아현점,Q,음식,Q07,패스트푸드,Q07A01,피자전문,I56192,...,1.141011e+24,,서울특별시 서대문구 신촌로 207,120822,3767,,1,,126.949133,37.557207

In [72]:
df_ter = pd.merge(df_food, df_best, on = 'place', how = 'inner')
df_ter

,bizesId,place,brchNm,indsLclsCd,indsLclsNm,indsMclsCd,indsMclsNm,indsSclsCd,indsSclsNm,ksicCd,...,rdnmAdr,oldZipcd,newZipcd,dongNo,flrNo,hoNo,lon,lat,rate,visit
0,17533468,진돈부리,,Q,음식,Q03,일식/수산물,Q03A02,음식점-일식,I56113,...,서울특별시 서대문구 신촌로 149,120809,3780,,1,,126.942483,37.556859,4.83,179
1,18143901,수퍼파인,,Q,음식,Q07,패스트푸드,Q07A05,샌드위치전문점,I56192,...,서울특별시 서대문구 신촌역로 17,120809,3780,,1,,126.942395,37.558282,,17
2,20630100,훈카츠,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,서울특별시 서대문구 신촌역로 15,120809,3780,,1,,126.942578,37.558148,4.7,202
3,16325619,영미김밥,,Q,음식,Q04,분식,Q04A01,라면김밥분식,I56194,...,서울특별시 서대문구 신촌역로 21,120809,3777,,,,126.942469,37.558652,4.57,"1,063"
4,23382559,미스터서왕만두,,Q,음식,Q04,분식,Q04A01,라면김밥분식,I56194,...,서울특별시 서대문구 신촌역로 16,120808,3766,,1,,126.943156,37.558054,4.49,353
5,20673833,아건,,Q,음식,Q06,양식,Q06A01,정통양식/경양식,I56114,...,서울특별시 서대문구 이화여대3길 35,120809,3766,,2,,126.943669,37.557834,4.82,"1,351"
6,16603185,아건,,Q,음식,Q10,별식/퓨전요리,Q10A08,동남아음식전문점,I56119,...,서울특별시 서대문구 이화여대길 63,120808,3766,,,,126.944908,37.559052,4.82,"1,351"
7,17010845,심플리키친,,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,서울특별시 서대문구 이화여대5길 35,120808,3766,,1,,126.943744,37.558123,4.68,191
8,17079357,원앤온리커피,,Q,음식,Q12,커피점/카페,Q12A01,커피전문점/카페/다방,I56220,...,서울특별시 서대문구 이화여대7길 31-4,120808,3766,,,,126.943772,37.558537,4.49,252
9,16638629,치즈문,,Q,음식,Q09,유흥주점,Q09A08,빠/카페/스탠드빠,I56211,...,서울특별시 서대문구 이화여대길 88-13,120808,3765,,,,126.943805,37.559385,4.91,94
10,21980103,플로루스,,Q,음식,Q08,제과제빵떡케익,Q08A01,제과점,I56191,...,서울특별시 서대문구 이화여대길 88-11,120809,3765,,,,126.943693,37.559347,,14
11,17933395,로컬식당,,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,서울특별시 서대문구 이화여대1길 33,120809,3766,,1,,126.943770,37.557114,,16
12,16294026,비아37,,Q,음식,Q06,양식,Q06A07,기타전문서양음식점,I56114,...,서울특별시 서대문구 이화여대길 77-1,120808,3766,,,,126.944117,37.558973,4.67,431
13,17838146,신화장,,Q,음식,Q02,중식,Q02A00,중국음식/중국집,I56112,...,서울특별시 서대문구 이화여대7길 30,120808,3766,,2,,126.943881,37.558818,4.67,24
14,23434871,파파노다이닝,,Q,음식,Q06,양식,Q06A01,정통양식/경양식,I56114,...,서울특별시 서대문구 이화여대길 88-14,120808,3765,,1,,126.944111,37.559414,4.56,505
15,17533548,리카,스시카야,Q,음식,Q03,일식/수산물,Q03A02,음식점-일식,I56113,...,서울특별시 서대문구 이화여대길 72-3,120808,3765,,2,,126.944372,37.559345,,28
16,18107441,굿바이슈가베어,,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,서울특별시 서대문구 이화여대길 72-6,120808,3765,,1,,126.944552,37.559427,4.83,180
17,16584804,청키파이,,Q,음식,Q12,커피점/카페,Q12A01,커피전문점/카페/다방,I56220,...,서울특별시 서대문구 신촌역로 22-5,120808,3766,,,,126.943020,37.558900,4.72,181
18,17009491,노란집,,Q,음식,Q06,양식,Q06A01,정통양식/경양식,I56114,...,서울특별시 서대문구 신촌역로 22-5,120808,3766,,2,,126.943020,37.558900,4.41,119
19,17011505,카페코지,,Q,음식,Q12,커피점/카페,Q12A01,커피전문점/카페/다방,I56220,...,서울특별시 서대문구 신촌역로 22-5,120808,3766,,2,,126.943020,37.558900,4.69,186
20,19968901,파가니니,,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,서울특별시 서대문구 이화여대길 63,120808,3766,,6,,126.944908,37.559052,4.59,81
21,17038461,한끼마끼,,Q,음식,Q04,분식,Q04A01,라면김밥분식,I56194,...,서울특별시 서대문구 이화여대1길 15,120808,3766,,,,126.944900,37.557205,4.61,236
22,12106104,다다,,Q,음식,Q06,양식,Q06A01,정통양식/경양식,I56114,...,서울특별시 서대문구 이화여대3길 14,120808,3766,,2,,126.944955,37.558115,4.45,250
23,16993798,천진분식,이대점,Q,음식,Q04,분식,Q04A01,라면김밥분식,I56194,...,서울특별시 서대문구 이화여대5길 7,120808,3766,,1,,126.945247,37.558271,4.71,222
24,17137238,모미지식당,,Q,음식,Q03,일식/수산물,Q03A02,음식점-일식,I56113,...,서울특별시 서대문구 이화여대5길 15,120808,3766,,2,,126.944817,37.558276,4.74,329
25,17156695,포케포케,,Q,음식,Q15,부페,Q15A01,종합부페,,...,서울특별시 서대문구 이화여대5길 15,120808,3766,,,,126.944817,37.558276,4.59,175
26,25730957,가야가야,,Q,음식,Q04,분식,Q04A01,라면김밥분식,I56194,...,서울특별시 서대문구 이화여대5길 7-3,120808,3766,,,,126.945362,37.558182,4.29,105
27,12568888,타이스토리,,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,서울특별시 서대문구 이화여대5길 2,120808,3766,,1,,126.945516,37.558445,4.38,62
28,19967677,빵사이에낀과일,,Q,음식,Q07,패스트푸드,Q07A04,패스트푸드,I56199,...,서울특별시 서대문구 이화여대길 45,120808,3766,,1,,126.945532,37.558931,4.6,161
29,17092421,세아마라탕,,Q,음식,Q02,중식,Q02A00,중국음식/중국집,I56112,...,서울특별시 서대문구 이화여대길 16,120808,3767,,,,126.945993,37.557584,4.27,175
30,18352531,방그레커피,,Q,음식,Q12,커피점/카페,Q12A01,커피전문점/카페/다방,I56220,...,서울특별시 마포구 대흥로 180,121808,4112,,1,,126.946164,37.555072,,20
31,18030884,유소바,,Q,음식,Q03,일식/수산물,Q03A02,음식점-일식,I56113,...,서울특별시 서대문구 이화여대2길 4,120808,3767,,1,,126.946145,37.557243,,249
32,17496872,원즈오운,,Q,음식,Q06,양식,Q06A01,정통양식/경양식,I56114,...,서울특별시 서대문구 이화여대길 20,120808,3767,,1,,126.946092,37.557747,4.46,224
33,17476457,하늘초밥,,Q,음식,Q03,일식/수산물,Q03A02,음식점-일식,I56113,...,서울특별시 서대문구 이화여대2길 14,120808,3767,,1,,126.946676,37.557302,4.66,190
34,17083541,폴어반,,Q,음식,Q06,양식,Q06A01,정통양식/경양식,I56114,...,서울특별시 서대문구 이화여대2길 11,120808,3767,,,,126.946492,37.557516,4.89,185
35,20280676,종금양꼬치,,Q,음식,Q09,유흥주점,Q09A03,꼬치구이전문점,I56219,...,서울특별시 마포구 대흥로30길 21,121870,4113,,1,,126.947208,37.556441,4.66,77
36,14084683,종금양꼬치,,Q,음식,Q09,유흥주점,Q09A03,꼬치구이전문점,I56219,...,서울특별시 마포구 대흥로30길 30,121870,4113,,,,126.947663,37.556319,4.66,77
37,16729867,내사랑,,Q,음식,Q12,커피점/카페,Q12A01,커피전문점/카페/다방,I56220,...,서울특별시 서대문구 이화여대2길 37,120808,3767,,,,126.947952,37.557511,4.34,62
38,12328064,만나김밥,,Q,음식,Q04,분식,Q04A01,라면김밥분식,I56194,...,서울특별시 서대문구 이화여대2다길 23,120808,3767,,1,,126.948076,37.558359,4.31,111

In [37]:
res_list= df_best['place'].to_list()
df_food[df_food['bizesNm'] == res_list[4]]

,bizesId,bizesNm,brchNm,indsLclsCd,indsLclsNm,indsMclsCd,indsMclsNm,indsSclsCd,indsSclsNm,ksicCd,...,bldMngNo,bldNm,rdnmAdr,oldZipcd,newZipcd,dongNo,flrNo,hoNo,lon,lat
787,17476457,하늘초밥,,Q,음식,Q03,일식/수산물,Q03A02,음식점-일식,I56113,...,1.141011e+24,,서울특별시 서대문구 이화여대2길 14,120808,3767,,1,,126.946676,37.557302

In [115]:
df_best = pd.read_json('./df_best2.json')
df_best

          place  rate visit
0          인생식당          14
1      디저트바 이브흐  4.91   258
2          공복식당  4.48   275
3         유야케도쿄  4.59   220
4          하늘초밥  4.66   190
..          ...   ...   ...
199  하루엔소쿠 이대역점           8
200     불밥 이대본점  4.46    96
201   쉬즈베이글 이대점  4.56   277
202       나이스샤워  4.46   204
203   박가네 찌개&볶음  4.42   145

[204 rows x 3 columns]

In [109]:
df_food

,bizesId,place,brchNm,indsLclsCd,indsLclsNm,indsMclsCd,indsMclsNm,indsSclsCd,indsSclsNm,ksicCd,...,bldMngNo,bldNm,rdnmAdr,oldZipcd,newZipcd,dongNo,flrNo,hoNo,lon,lat
4,11980901,팔색,,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,1.141011e+24,신촌자이엘라,서울특별시 서대문구 신촌로 149,120809,3780,,1,,126.942483,37.556859
5,12033685,포원제로410,,Q,음식,Q06,양식,Q06A01,정통양식/경양식,I56114,...,1.141011e+24,신촌자이엘라,서울특별시 서대문구 신촌로 149,120809,3780,,1,,126.942483,37.556859
11,16553616,밥이꿀바비꿀,,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,1.141011e+24,신촌자이엘라,서울특별시 서대문구 신촌로 149,120809,3780,101,,,126.942483,37.556859
12,16701604,투다리,이대점,Q,음식,Q09,유흥주점,Q09A07,기타일반유흥주점,I56211,...,1.141011e+24,신촌자이엘라,서울특별시 서대문구 신촌로 149,120809,3780,,,,126.942483,37.556859
13,16860055,벨르,,Q,음식,Q12,커피점/카페,Q12A01,커피전문점/카페/다방,I56220,...,1.141011e+24,신촌자이엘라,서울특별시 서대문구 신촌로 149,120809,3780,101,,,126.942483,37.556859
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
943,12482161,플러스알파카페,,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,1.141011e+24,핀란드타워,서울특별시 서대문구 신촌로 203,120808,3767,,2,,126.948488,37.557201
944,15958983,마이헬싱키까페,,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,1.141011e+24,핀란드타워,서울특별시 서대문구 신촌로 203,120808,3767,,-2,,126.948488,37.557201
947,26031006,고향순대감자탕,,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,1.144011e+24,,서울특별시 마포구 대흥로24길 50,121870,4123,,1,,126.948656,37.554905
952,11755132,파파존스피자,이대아현점,Q,음식,Q06,양식,Q06A01,정통양식/경양식,I56114,...,1.141011e+24,,서울특별시 서대문구 신촌로 207,120822,3767,,2,,126.949133,37.557207
953,12452641,파파존스이대아현점,이대아현점,Q,음식,Q07,패스트푸드,Q07A01,피자전문,I56192,...,1.141011e+24,,서울특별시 서대문구 신촌로 207,120822,3767,,1,,126.949133,37.557207

In [57]:
pd.merge('df_food','df_best', left_on = 'bizesNm',
    right_on='place', how = 'outer')

In [61]:
df_food.join(df_best, how = 'inner')

,bizesId,bizesNm,brchNm,indsLclsCd,indsLclsNm,indsMclsCd,indsMclsNm,indsSclsCd,indsSclsNm,ksicCd,...,oldZipcd,newZipcd,dongNo,flrNo,hoNo,lon,lat,place,rate,visit
4,11980901,팔색,,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,120809,3780,,1,,126.942483,37.556859,하늘초밥,4.66,190
5,12033685,포원제로410,,Q,음식,Q06,양식,Q06A01,정통양식/경양식,I56114,...,120809,3780,,1,,126.942483,37.556859,마더린러 베이글,,714
11,16553616,밥이꿀바비꿀,,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,120809,3780,101,,,126.942483,37.556859,유소바,,249
12,16701604,투다리,이대점,Q,음식,Q09,유흥주점,Q09A07,기타일반유흥주점,I56211,...,120809,3780,,,,126.942483,37.556859,공릉닭한마리,4.45,433
13,16860055,벨르,,Q,음식,Q12,커피점/카페,Q12A01,커피전문점/카페/다방,I56220,...,120809,3780,101,,,126.942483,37.556859,그릭데이 이대본점,4.71,"3,098"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191,17465035,주앙곰컴퍼니,,Q,음식,Q04,분식,Q04A01,라면김밥분식,I56194,...,120809,3765,,1,,126.943580,37.559328,모도크로플 이대점,,22
193,19967963,인생이야기,,Q,음식,Q12,커피점/카페,Q12A01,커피전문점/카페/다방,I56220,...,120809,3765,,3,,126.943661,37.559212,고스트요거트 이대점,4.8,906
194,21980103,플로루스,,Q,음식,Q08,제과제빵떡케익,Q08A01,제과점,I56191,...,120809,3765,,,,126.943693,37.559347,아리랑노점 이대본점,,19
196,23417732,솔리드웍스,,Q,음식,Q09,유흥주점,Q09A08,빠/카페/스탠드빠,I56211,...,120809,3765,,1,,126.943479,37.559273,다다,4.45,250
201,16984313,미혜식당,,Q,음식,Q02,중식,Q02A00,중국음식/중국집,I56112,...,120809,3765,,,,126.943769,37.559528,쉬즈베이글 이대점,4.56,277

In [77]:
df_ter.sort_values('rate', ascending = False).head()

,bizesId,place,brchNm,indsLclsCd,indsLclsNm,indsMclsCd,indsMclsNm,indsSclsCd,indsSclsNm,ksicCd,...,rdnmAdr,oldZipcd,newZipcd,dongNo,flrNo,hoNo,lon,lat,rate,visit
9,16638629,치즈문,,Q,음식,Q09,유흥주점,Q09A08,빠/카페/스탠드빠,I56211,...,서울특별시 서대문구 이화여대길 88-13,120808,3765,,,,126.943805,37.559385,4.91,94
34,17083541,폴어반,,Q,음식,Q06,양식,Q06A01,정통양식/경양식,I56114,...,서울특별시 서대문구 이화여대2길 11,120808,3767,,,,126.946492,37.557516,4.89,185
0,17533468,진돈부리,,Q,음식,Q03,일식/수산물,Q03A02,음식점-일식,I56113,...,서울특별시 서대문구 신촌로 149,120809,3780,,1,,126.942483,37.556859,4.83,179
16,18107441,굿바이슈가베어,,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,서울특별시 서대문구 이화여대길 72-6,120808,3765,,1,,126.944552,37.559427,4.83,180
5,20673833,아건,,Q,음식,Q06,양식,Q06A01,정통양식/경양식,I56114,...,서울특별시 서대문구 이화여대3길 35,120809,3766,,2,,126.943669,37.557834,4.82,"1,351"

In [112]:
df_ter['visit'] = pd.to_numeric(df_ter["visit"].str.replace(',', ''))

AttributeError: Can only use .str accessor with string values!

In [89]:
df_ter.sort_values('visit', ascending = False).head()

,bizesId,place,brchNm,indsLclsCd,indsLclsNm,indsMclsCd,indsMclsNm,indsSclsCd,indsSclsNm,ksicCd,...,rdnmAdr,oldZipcd,newZipcd,dongNo,flrNo,hoNo,lon,lat,rate,visit
5,20673833,아건,,Q,음식,Q06,양식,Q06A01,정통양식/경양식,I56114,...,서울특별시 서대문구 이화여대3길 35,120809,3766,,2,,126.943669,37.557834,4.82,1351
6,16603185,아건,,Q,음식,Q10,별식/퓨전요리,Q10A08,동남아음식전문점,I56119,...,서울특별시 서대문구 이화여대길 63,120808,3766,,,,126.944908,37.559052,4.82,1351
3,16325619,영미김밥,,Q,음식,Q04,분식,Q04A01,라면김밥분식,I56194,...,서울특별시 서대문구 신촌역로 21,120809,3777,,,,126.942469,37.558652,4.57,1063
14,23434871,파파노다이닝,,Q,음식,Q06,양식,Q06A01,정통양식/경양식,I56114,...,서울특별시 서대문구 이화여대길 88-14,120808,3765,,1,,126.944111,37.559414,4.56,505
12,16294026,비아37,,Q,음식,Q06,양식,Q06A07,기타전문서양음식점,I56114,...,서울특별시 서대문구 이화여대길 77-1,120808,3766,,,,126.944117,37.558973,4.67,431

TypeError: string indices must be integers