In [50]:
# 맛집 검색 및 별점, 방문자리뷰 수 크롤링
import time
import selenium
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

import requests
from bs4 import BeautifulSoup
import re
import csv
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

path = 'C:/Users/sch014/working/git_mine/Toddbear20/m2_분석라이브러리활용/crawling/chromedriver.exe'
options = webdriver.ChromeOptions()

driver = webdriver.Chrome(path, options=options)
driver.implicitly_wait(time_to_wait=3)

driver.get("https://map.naver.com/v5/") 
try:
    element = WebDriverWait(driver, 10).until(
       EC.presence_of_element_located((By.CLASS_NAME, "input_search"))
   ) #입력창이 뜰 때까지 대기
finally:
    pass

search_box = driver.find_element(By.CLASS_NAME,"input_search")
search_box.send_keys("이대역맛집")
search_box.send_keys(Keys.ENTER)
time.sleep(4)

frame = driver.find_element(By.CSS_SELECTOR,"iframe#searchIframe")

driver.switch_to.frame(frame)

time.sleep(3)
# 여기까지 iframe 전환

scroll_div = driver.find_element(By.XPATH,"/html/body/div[3]/div/div[2]/div[1]")
#검색 결과로 나타나는 scroll-bar 포함한 div 잡고
driver.execute_script("arguments[0].scrollBy(0,2000)", scroll_div)
time.sleep(2)
driver.execute_script("arguments[0].scrollBy(0,2000);", scroll_div)
time.sleep(2)
driver.execute_script("arguments[0].scrollBy(0,2000);", scroll_div)
time.sleep(2)
driver.execute_script("arguments[0].scrollBy(0,2000);", scroll_div)
time.sleep(2)
driver.execute_script("arguments[0].scrollBy(0,2000);", scroll_div)
time.sleep(2)

final_result = []

i = 2
while i<=5: #몇 페이지까지 크롤링할 것인지 지정
    stores = driver.find_elements(By.CSS_SELECTOR,"#_pcmap_list_scroll_container > ul > li")
   #해당 페이지에서 표시된 모든 가게 정보
   
    for store in stores: #한 페이지 내에서의 반복문. 순차적으로 가게 정보에 접근
        name = store.find_element(By.CSS_SELECTOR,"#_pcmap_list_scroll_container > ul > li> div > a > div > div > span.place_bluelink.OXiLu").text #가게 이름
        
        try:    
            rating = re.search('(\d.\d+)', store.find_element(By.CSS_SELECTOR,"#_pcmap_list_scroll_container > ul > li > div > div > span > em").get_attribute('innerHTML')).groups()[0]
        except:
            rating = ''
        try:
            visit = re.sub('[^\d+,]','',store.find_element(By.CSS_SELECTOR,'#_pcmap_list_scroll_container > ul > li > div._3hn9q > div._17H46 > span:nth-child(3)').text)
        except:
            visit = ''
        
#         click_name = store.find_element(By.CSS_SELECTOR,"#_pcmap_list_scroll_container > ul > li > div > a > div > div > span.place_bluelink.OXiLu")
#         click_name.click() 
        
#         driver.switch_to.default_content()
#         time.sleep(4)  
        
#         frame_in = driver.find_element(By.XPATH,'/html/body/app/layout/div[3]/div[2]/shrinkable-layout/div/app-base/search-layout/div[2]/entry-layout/entry-place-bridge/div/nm-external-frame-bridge/nm-iframe/iframe')
#         driver.switch_to.frame(frame_in) 
#         time.sleep(3)
        
#         try:
#             address = re.search('>[서울\w+]<', driver.find_element(By.CSS_SELECTOR,"#app-root > div > div > div > div > div > div > div > ul > li > div > a > span._2yqUQ").text)
#         except:
#             address = ''
#         try:
#             visit = re.search('(\d+)',store.find_element(By.CSS_SELECTOR,'#app-root > div > div > div > div > div > div > span > a > em').get_attribute('innerHTML')).groups()[0]
#         except:
#             visit = ''
        
        store_info = {
           'place':name,
           'rate':rating, 'visit':visit}
        
        final_result.append(store_info)
        
#         driver.switch_to.default_content()
#         driver.switch_to.frame(frame)
        
        time.sleep(3)
     
    next_button = driver.find_element(By.LINK_TEXT, str(i))
    next_button.click()
    i = i+1
    time.sleep(5)
    
print(final_result)

[{'place': '인생식당', 'rate': '', 'visit': '14'}, {'place': '디저트바 이브흐', 'rate': '4.91', 'visit': '258'}, {'place': '공복식당', 'rate': '4.48', 'visit': '275'}, {'place': '유야케도쿄', 'rate': '4.59', 'visit': '220'}, {'place': '하늘초밥', 'rate': '4.66', 'visit': '190'}, {'place': '마더린러 베이글', 'rate': '', 'visit': '714'}, {'place': '라구식당', 'rate': '4.48', 'visit': '807'}, {'place': '비밀', 'rate': '4.4', 'visit': '866'}, {'place': '위샐러듀 이대점', 'rate': '4.61', 'visit': '3,690'}, {'place': '정정', 'rate': '', 'visit': '302'}, {'place': '연어초밥', 'rate': '4.67', 'visit': '1,067'}, {'place': '유소바', 'rate': '', 'visit': '249'}, {'place': '공릉닭한마리', 'rate': '4.45', 'visit': '433'}, {'place': '그릭데이 이대본점', 'rate': '4.71', 'visit': '3,098'}, {'place': '티앙팡 오후의 홍차', 'rate': '4.5', 'visit': '325'}, {'place': '방콕익스프레스 신촌본점', 'rate': '4.37', 'visit': '722'}, {'place': '키친봄날', 'rate': '4.78', 'visit': '1,572'}, {'place': '비아37', 'rate': '4.67', 'visit': '431'}, {'place': '진돈부리', 'rate': '4.83', 'visit': '179'}, {'place': '내사랑', 'rate': '4.34', 'visit': '62'}, {'place': '호밀밭', 'rate': '4.62', 'visit': '967'}, {'place': '원즈오운', 'rate': '4.46', 'visit': '224'}, {'place': '그릭데이 이대본점', 'rate': '4.71', 'visit': '3,098'}, {'place': '자마버거 이대점', 'rate': '4.27', 'visit': '126'}, {'place': '금별맥주 신촌직영점', 'rate': '4.44', 'visit': '497'}, {'place': '한끼마끼', 'rate': '4.61', 'visit': '236'}, {'place': '아건', 'rate': '4.82', 'visit': '1,351'}, {'place': '고냉지', 'rate': '4.53', 'visit': '423'}, {'place': '황금콩밭', 'rate': '4.36', 'visit': '1,271'}, {'place': '란주탕슉', 'rate': '4.41', 'visit': '779'}, {'place': '유원섬커피', 'rate': '4.44', 'visit': '153'}, {'place': '오늘통닭 신촌직영점', 'rate': '4.47', 'visit': '515'}, {'place': '킬더유튜브', 'rate': '', 'visit': '9'}, {'place': '가야가야', 'rate': '4.29', 'visit': '105'}, {'place': '삭 수제튀김 전문점', 'rate': '4.46', 'visit': '752'}, {'place': '카페페라', 'rate': '', 'visit': '302'}, {'place': '사장님돈까스 이화여대점', 'rate': '4.63', 'visit': '574'}, {'place': '하루식당', 'rate': '4.69', 'visit': '77'}, {'place': '시내당', 'rate': '', 'visit': '23'}, {'place': '여래여거', 'rate': '4.95', 'visit': '121'}, {'place': '낭만식탁', 'rate': '', 'visit': '174'}, {'place': '에그 앤드 스푼레이스', 'rate': '4.5', 'visit': '416'}, {'place': '가미분식', 'rate': '4.43', 'visit': '342'}, {'place': '라화쿵부 신촌점', 'rate': '4.69', 'visit': '1,488'}, {'place': '대현매운족발 본점', 'rate': '4.5', 'visit': '164'}, {'place': '벤치커피스튜디오', 'rate': '4.63', 'visit': '189'}, {'place': '유자유김치떡볶이 신촌점', 'rate': '4.6', 'visit': '218'}, {'place': '까이식당', 'rate': '4.55', 'visit': '175'}, {'place': '미스터서왕만두', 'rate': '4.49', 'visit': '353'}, {'place': '방그레커피', 'rate': '', 'visit': '20'}, {'place': '영미김밥', 'rate': '4.57', 'visit': '1,063'}, {'place': '아소비바', 'rate': '', 'visit': '10'}, {'place': '전골떡볶이 덕미가 이대본점', 'rate': '4.48', 'visit': '206'}, {'place': '1987피자', 'rate': '4.77', 'visit': '102'}, {'place': '훈카츠', 'rate': '4.7', 'visit': '202'}, {'place': '아웃백스테이크하우스 신촌점', 'rate': '4.47', 'visit': '5,550'}, {'place': '텐동미세기', 'rate': '4.44', 'visit': '369'}, {'place': '청키파이', 'rate': '4.72', 'visit': '181'}, {'place': '원앤온리커피', 'rate': '4.49', 'visit': '252'}, {'place': '반타이 쏘이54', 'rate': '4.56', 'visit': '168'}, {'place': 'waffle it up', 'rate': '4.63', 'visit': '576'}, {'place': '이름없는파스타 이화여대점', 'rate': '4.4', 'visit': '291'}, {'place': '솔리드웍스 아이스크림', 'rate': '', 'visit': '146'}, {'place': '너스레', 'rate': '4.59', 'visit': '312'}, {'place': '파파노다이닝', 'rate': '4.56', 'visit': '505'}, {'place': '카라멘야', 'rate': '4.47', 'visit': '1,025'}, {'place': '스시가마시 이대점', 'rate': '4.34', 'visit': '206'}, {'place': '인생식당', 'rate': '', 'visit': '14'}, {'place': '카페아늑', 'rate': '4.61', 'visit': '108'}, {'place': '소바연구소', 'rate': '4.53', 'visit': '633'}, {'place': '아웃닭 이대점', 'rate': '4.57', 'visit': '320'}, {'place': '커피도가 헤리티지 신촌이대점', 'rate': '4.72', 'visit': '126'}, {'place': '마포투뿔', 'rate': '4.13', 'visit': '163'}, {'place': '로컬식당', 'rate': '', 'visit': '16'}, {'place': '청년다방 신촌점', 'rate': '4.39', 'visit': '718'}, {'place': '명륜진사갈비 서울신촌점', 'rate': '4.21', 'visit': '649'}, {'place': '칭닌', 'rate': '4.5', 'visit': '713'}, {'place': '노란집', 'rate': '4.41', 'visit': '119'}, {'place': 'BHC치킨 이대역점', 'rate': '4.35', 'visit': '192'}, {'place': 'veganique', 'rate': '4.58', 'visit': '146'}, {'place': '전티마이베트남쌀국수 이화여대점', 'rate': '4.41', 'visit': '424'}, {'place': '모미지식당', 'rate': '4.74', 'visit': '329'}, {'place': '청년밥상문간 이화여자대학교점', 'rate': '', 'visit': '70'}, {'place': '세아마라탕', 'rate': '4.27', 'visit': '175'}, {'place': '모음', 'rate': '', 'visit': '35'}, {'place': '고삼이 신촌점', 'rate': '4.56', 'visit': '353'}, {'place': '카페페라유니크', 'rate': '', 'visit': '102'}, {'place': '누들김밥 이대점', 'rate': '4.53', 'visit': '323'}, {'place': '베러댄와플 이화여대점', 'rate': '4.67', 'visit': '446'}, {'place': '신촌장군집', 'rate': '', 'visit': '38'}, {'place': '고피자 신촌1호점', 'rate': '4.4', 'visit': '342'}, {'place': '막걸리싸롱', 'rate': '4.45', 'visit': '74'}, {'place': '제임스시카고피자 신촌점', 'rate': '4.56', 'visit': '104'}, {'place': '스타벅스 이대R점', 'rate': '4.49', 'visit': '2,107'}, {'place': '뉴타운', 'rate': '4.42', 'visit': '127'}, {'place': '자마버거 이대점', 'rate': '4.27', 'visit': '126'}, {'place': '카페코지', 'rate': '4.69', 'visit': '186'}, {'place': '어바웃샤브 이대점', 'rate': '4.49', 'visit': '325'}, {'place': '돈까스대왕전 이대점', 'rate': '4.41', 'visit': '1,161'}, {'place': '파가니니', 'rate': '4.59', 'visit': '81'}, {'place': '브릭스5221 신촌점', 'rate': '4.65', 'visit': '154'}, {'place': '이삭토스트 이화여대점', 'rate': '4.63', 'visit': '641'}, {'place': '아콘스톨', 'rate': '4.7', 'visit': '281'}, {'place': '범이네부엌', 'rate': '', 'visit': '63'}, {'place': '초식곳간', 'rate': '4.78', 'visit': '333'}, {'place': '밀리네해물잡탕', 'rate': '4.27', 'visit': '202'}, {'place': '신전떡볶이 서울신촌점', 'rate': '4.39', 'visit': '760'}, {'place': '앨리스', 'rate': '4.56', 'visit': '100'}, {'place': '와플칸 마포점', 'rate': '4.42', 'visit': '226'}, {'place': '후쿠스시', 'rate': '4.66', 'visit': '146'}, {'place': '타이스토리', 'rate': '4.38', 'visit': '62'}, {'place': '써브웨이 이대점', 'rate': '4.54', 'visit': '914'}, {'place': '리또리또', 'rate': '4.56', 'visit': '270'}, {'place': '신참떡볶이 이대점', 'rate': '4.36', 'visit': '488'}, {'place': '강릉아구찜', 'rate': '4.34', 'visit': '91'}, {'place': 'LAFL', 'rate': '4.83', 'visit': '121'}, {'place': '모센즈스위트 이대점', 'rate': '', 'visit': '6'}, {'place': '디델리 이대점', 'rate': '4.56', 'visit': '163'}, {'place': '폼프리츠 신촌점', 'rate': '4.55', 'visit': '180'}, {'place': '포원제로 버거 신촌', 'rate': '', 'visit': '66'}, {'place': '라헬의부엌 이대점', 'rate': '', 'visit': '44'}, {'place': '오롯', 'rate': '4.48', 'visit': '742'}, {'place': '천진분식', 'rate': '4.71', 'visit': '222'}, {'place': '플라페', 'rate': '', 'visit': '21'}, {'place': '리카', 'rate': '', 'visit': '28'}, {'place': '빵사이에낀과일', 'rate': '4.6', 'visit': '161'}, {'place': '유', 'rate': '4.59', 'visit': '138'}, {'place': '볶음쌈밥', 'rate': '4.58', 'visit': '107'}, {'place': '치즈문', 'rate': '4.91', 'visit': '94'}, {'place': '팜스힐', 'rate': '', 'visit': '19'}, {'place': '누아네', 'rate': '4.46', 'visit': '721'}, {'place': '산타비', 'rate': '4.61', 'visit': '83'}, {'place': '신화장', 'rate': '4.67', 'visit': '24'}, {'place': 'studio123', 'rate': '4.26', 'visit': '140'}, {'place': '플로루스', 'rate': '', 'visit': '14'}, {'place': '나주곰탕냉면 본점', 'rate': '', 'visit': '24'}, {'place': '마포깐풍기', 'rate': '4.49', 'visit': '125'}, {'place': '마라탕 이대6호점', 'rate': '4.52', 'visit': '269'}, {'place': '카페27도씨', 'rate': '4.92', 'visit': '204'}, {'place': '웅네서서갈비', 'rate': '4.45', 'visit': '386'}, {'place': '밀밭정원', 'rate': '4.24', 'visit': '163'}, {'place': '빵을집다', 'rate': '4.71', 'visit': '294'}, {'place': '종금양꼬치', 'rate': '4.66', 'visit': '77'}, {'place': '써니보울', 'rate': '', 'visit': '44'}, {'place': '심플리키친', 'rate': '4.68', 'visit': '191'}, {'place': '파스텔드나따 이대점', 'rate': '4.61', 'visit': '467'}, {'place': '빌리지 신촌점', 'rate': '4.45', 'visit': '70'}, {'place': '산청자매훠궈 이대점', 'rate': '4.27', 'visit': '81'}, {'place': '팔색콩불', 'rate': '4.79', 'visit': '28'}, {'place': '장군닭갈비 신촌점', 'rate': '4.45', 'visit': '174'}, {'place': '폴어반', 'rate': '4.89', 'visit': '185'}, {'place': '굿바이슈가베어', 'rate': '4.83', 'visit': '180'}, {'place': 'Liebhaber', 'rate': '4.49', 'visit': '206'}, {'place': 'the Panini', 'rate': '4.77', 'visit': '47'}, {'place': '이화성', 'rate': '4.3', 'visit': '287'}, {'place': '이코노스시본점', 'rate': '4.35', 'visit': '175'}, {'place': '쿠리야', 'rate': '', 'visit': '4'}, {'place': '다발김치찌개', 'rate': '4.39', 'visit': '149'}, {'place': '비아 메렝게', 'rate': '4.4', 'visit': '188'}, {'place': '할리스 이대점', 'rate': '4.43', 'visit': '1,007'}, {'place': '띵크 샐러', 'rate': '4.6', 'visit': '447'}, {'place': '백암순대국', 'rate': '4.45', 'visit': '183'}, {'place': '만나김밥', 'rate': '4.31', 'visit': '111'}, {'place': '라장훠궈', 'rate': '4.38', 'visit': '207'}, {'place': '개미집 신촌점', 'rate': '4.34', 'visit': '257'}, {'place': '아임요거트&아이스크림 이화점', 'rate': '', 'visit': '4'}, {'place': '포케포케', 'rate': '4.59', 'visit': '175'}, {'place': '메가커피 이대점', 'rate': '', 'visit': '15'}, {'place': '김광석신촌칼국수 이대직영점', 'rate': '4.28', 'visit': '427'}, {'place': '꽃피다이화다방', 'rate': '4.56', 'visit': '196'}, {'place': '홍도깨비 2호점', 'rate': '4.4', 'visit': '59'}, {'place': '승미곱창', 'rate': '4.43', 'visit': '97'}, {'place': '부성감자탕', 'rate': '4.34', 'visit': '120'}, {'place': '육수당 이대역점', 'rate': '4.32', 'visit': '445'}, {'place': '카페마지오', 'rate': '4.48', 'visit': '412'}, {'place': '벨라프라하', 'rate': '4.68', 'visit': '455'}, {'place': '와인집', 'rate': '4.88', 'visit': '50'}, {'place': '수퍼파인', 'rate': '', 'visit': '17'}, {'place': '배스킨라빈스 이대역', 'rate': '4.47', 'visit': '851'}, {'place': '포석정', 'rate': '4.53', 'visit': '190'}, {'place': '우드문', 'rate': '', 'visit': '23'}, {'place': '낮과밤', 'rate': '4.54', 'visit': '128'}, {'place': '에그셀런트 이대점', 'rate': '4.68', 'visit': '7'}, {'place': '천장어 마포점', 'rate': '4.26', 'visit': '369'}, {'place': '수라', 'rate': '4.37', 'visit': '142'}, {'place': '파스타리코 신촌점', 'rate': '4.44', 'visit': '266'}, {'place': '파리바게뜨 카페이대역점', 'rate': '4.4', 'visit': '1,930'}, {'place': '홍호아 신촌점', 'rate': '4.69', 'visit': '147'}, {'place': '제주도로담', 'rate': '4.49', 'visit': '149'}, {'place': '카츠난반', 'rate': '', 'visit': '36'}, {'place': '소녀방앗간 이화여대점', 'rate': '4.4', 'visit': '218'}, {'place': '모도크로플 이대점', 'rate': '', 'visit': '22'}, {'place': '붕메리카노', 'rate': '4.79', 'visit': '102'}, {'place': '고스트요거트 이대점', 'rate': '4.8', 'visit': '906'}, {'place': '아리랑노점 이대본점', 'rate': '', 'visit': '19'}, {'place': '리틀방콕 공덕경의선숲길점', 'rate': '4.33', 'visit': '309'}, {'place': '다다', 'rate': '4.45', 'visit': '250'}, {'place': '투썸플레이스 이대역점', 'rate': '4.43', 'visit': '1,854'}, {'place': '투고샐러드 신촌점', 'rate': '4.4', 'visit': '252'}, {'place': '하루엔소쿠 이대역점', 'rate': '', 'visit': '8'}, {'place': '불밥 이대본점', 'rate': '4.46', 'visit': '96'}, {'place': '쉬즈베이글 이대점', 'rate': '4.56', 'visit': '277'}, {'place': '나이스샤워', 'rate': '4.46', 'visit': '204'}, {'place': '박가네 찌개&볶음', 'rate': '4.42', 'visit': '145'}]

In [2]:
import pandas as pd
import json
df = pd.DataFrame(final_result)
df.to_json('df_best2.json', orient='columns')

NameError: name 'final_result' is not defined

In [12]:
import pandas as pd
df2 = pd.read_json('./df_best2.json')
df2

          place  rate visit
0          인생식당          14
1      디저트바 이브흐  4.91   258
2          공복식당  4.48   275
3         유야케도쿄  4.59   220
4          하늘초밥  4.66   190
..          ...   ...   ...
199  하루엔소쿠 이대역점           8
200     불밥 이대본점  4.46    96
201   쉬즈베이글 이대점  4.56   277
202       나이스샤워  4.46   204
203   박가네 찌개&볶음  4.42   145

[204 rows x 3 columns]

In [13]:
df2.sort_values(by=df2.columns[1],ascending=False)

           place  rate visit
39          여래여거  4.95   121
138       카페27도씨  4.92   204
128          치즈문  4.91    94
1       디저트바 이브흐  4.91   258
150          폴어반  4.89   185
..           ...   ...   ...
167     메가커피 이대점          15
62   솔리드웍스 아이스크림         146
51          아소비바          10
49         방그레커피          20
0           인생식당          14

[204 rows x 3 columns]

In [11]:
df2.sort_values(by=df2.columns[-1], ascending=True)

          place  rate  visit
159     할리스 이대점  4.43  1,007
65         카라멘야  4.47  1,025
50         영미김밥  4.57  1,063
10         연어초밥  4.67  1,067
98   돈까스대왕전 이대점  4.41  1,161
..          ...   ...    ...
111    써브웨이 이대점  4.54    914
128         치즈문  4.91     94
200     불밥 이대본점  4.46     96
20          호밀밭  4.62    967
171        승미곱창  4.43     97

[204 rows x 3 columns]