In [2]:
import pandas as pd
import numpy as np

order = pd.read_excel('./엑셀분리기본파일/자재발주기본.xlsx', header=1)
order.drop('Unnamed: 0',axis=1, inplace =True)
order

,발주번호,"발주구분(계획, 추가)",원자재코드,거래처코드,발주수량,발주단가,발주예정일자,발주일자,입고예정일자,입고일자,입고수량,회계일자,입고완료여부,발주서전송구분,발주서출력횟수,비고
0,B20210215-0001,계획,SR11002,2002100,877035.0,1000,2021-02-15,2021-02-15,2021-02-18,2021-02-21,877035.0,2021-02-25,Y,Y,1,NaN
1,B20210215-0002,계획,SR13801,2002200,2787.6,1100,2021-02-15,2021-02-15,2021-02-18,2021-02-21,2787.6,2021-02-25,Y,Y,1,NaN
2,B20210215-0003,계획,SR15500,2002300,5265.0,1300,2021-02-15,2021-02-15,2021-02-18,2021-02-21,5265.0,2021-02-25,Y,Y,1,NaN
3,B20210215-0004,계획,SR16002,2002400,7445.0,1000,2021-02-15,2021-02-15,2021-02-18,2021-02-21,7445.0,2021-02-25,Y,Y,1,NaN
4,B20210215-0005,계획,SR16003,2002500,1100.0,1100,2021-02-15,2021-02-15,2021-02-18,2021-02-21,1100.0,2021-02-25,Y,Y,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305,B20210419-0027,계획,SR35904,2002900,51463.0,1100,2021-04-19,2021-04-19,2021-04-22,2021-04-25,51463.0,2021-04-25,Y,Y,1,NaN
306,B20210419-0028,계획,SR35905,2002100,1100.0,1300,2021-04-19,2021-04-19,2021-04-22,2021-04-25,1100.0,2021-04-25,Y,Y,1,NaN
307,B20210419-0029,계획,SR38117,2002200,359.8,1000,2021-04-19,2021-04-19,2021-04-22,2021-04-25,359.8,2021-04-25,Y,Y,1,NaN
308,B20210419-0030,계획,SR47093,2002300,1100.0,1000,2021-04-19,2021-04-19,2021-04-22,2021-04-25,1100.0,2021-04-25,Y,Y,1,NaN
309,B20210419-0031,계획,SR68222,2002400,708.4,1100,2021-04-19,2021-04-19,2021-04-22,2021-04-25,708.4,2021-04-25,Y,Y,1,NaN

In [5]:
days=order['입고일자']-order['발주일자']

In [9]:
days.sum()

Timedelta('1860 days 00:00:00')